-- Update vendor password hash with the one generated by the backend
UPDATE users 
SET password_hash = '$2a$10$T16Nl0.8e9kEXDV2CN2FAee3hhp9TCBpEybi6QnmaRz3eNZOFFDO6'
WHERE email = 'vendor@restaurant.com';

-- Verify
SELECT email, role, vendor_status, 
       SUBSTRING(password_hash, 1, 30) || '...' as hash_preview
FROM users 
WHERE email = 'vendor@restaurant.com';
